version: "3.9"
services:
  server:
    image: carlasim/carla:0.9.11
    ports:
        - "2004-2006:2004-2006"
    command: ./CarlaUE4.sh -opengl -quality-level=low -world-port=2004
    runtime: nvidia
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - SDL_VIDEODRIVER=offscreen

  client:
    build: .
    links:
        - "server:carla"
    runtime: nvidia
    command: sh get_batches.sh
    volumes:
        - /home/johnny/Escritorio/data/:/home/carla_collector/data/
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
        - server
